### ISSUE TITLE
Bower registration

### ISSUE THREAD

**Issue by desandro** [warpdesign/deferred-js#5]
Hi there! I'm moving discussion from https://github.com/bower/bower/issues/120#issuecomment-67171170 over here.  Thanks for looking into adding bower support.

`deferred-js` is currently registered to [iam4x/deferred-js-bower](https://github.com/iam4x/deferred-js-bower/). It is a port of this repo, but I don't feel comfortable switching it over.

1. It's source directory is different from this one, i.e. `/deferred.js` vs `/js/deferred.js`
2. This repo is missing a `bower.json`

I feel the best solution is to register this repo under a different name, like `standalone-deferred` or even just `deferred`. This way, we don't break compatibility with `deferred-js-bower`.

**Comment by iam4x** [comment]
Hello @desandro @warpdesign, tell me when you want to switch. I'm okay with it, but let's do it in the same hour together so we don't break projects depending on it.

**Comment by warpdesign** [comment]
I hadn't noticed your messages, sorry about that.
It seems it's still registered. @iam4x can we agree on an hour then ? What about today 18h (GMT) ?
Thank you.

**Comment by iam4x** [comment]
@warpdesign Sorry didn't see, I did unregister the package today.

**Comment by warpdesign** [comment]
I have registered it as deferred-js, thanks @iam4x !
